[control]
10.8.244.214

[workers]
10.8.244.215
10.8.244.216
10.8.244.217

[all_nodes:children]
control
workers

[all_nodes:vars]
ansible_user=ubuntu

[control:vars]
node_role=master

[workers:vars]
node_role=worker
