site_name: Polaris Documentation
site_description: Eurac EO Argo CD cluster configuration and application deployments
docs_dir: docs/wiki
site_dir: site

theme:
    name: material
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode

        - scheme: slate
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.top
        - search.highlight
        - search.suggest
        - toc.integrate
        - content.code.annotate
        - content.code.copy
        - content.code.fold

nav:
    - Home: index.md
    - Install: installation.md
    - Uninstall: uninstall.md
    - Secrets: secrets.md
    - Multinode:

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - admonition
    - pymdownx.details
