apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: openeo-argoworkflows
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: polaris
    source:
        repoURL: https://github.com/Eurac-Research-Institute-for-EO/polaris
        targetRevision: main
        path: apps/openeo-argoworkflows
    destination:
        name: in-cluster
        namespace: openeo
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - Validate=true
            - CreateNamespace=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
            - RespectIgnoreDifferences=true
            - ApplyOutOfSyncOnly=true
